name: Build and release Locus

on: 
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check if Locus needs a re-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compare latest release
        run: |
          bash scripts/release_check.sh
  
  build:
    name: Build Locus
    runs-on: macos-14
    needs: check
    
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2.0
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Get Locus source code
        run: |
          mkdir gitignore && cd gitignore
          curl -LOJ $(curl -Ls https://api.github.com/repos/Myzel394/locus/releases/latest | grep \"zipball_url\" -m 1 | head -1 | tr -d ', ' | sed 's/"//g' | sed 's/zipball_url://g')
          unzip ./*.zip -d locus
          cd locus && cd ./*
          export RMDIR=$PWD
          mv ./* .. && cd ${{ github.workspace }} && rmdir $RMDIR
      - name: Build Locus
        run: |
          sudo xcodebuild -license accept && xcodebuild -downloadPlatform iOS
          cd gitignore/locus && flutter config --no-analytics && flutter --disable-telemetry && flutter build ipa --no-codesign && cd ${{ github.workspace }}
      - name: Update release.txt
        run: |
          mv release2.txt release.txt

  actions:
    name: Upload Actions artifacts
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Upload source code with build folder
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: gitignore/locus
      - name: Upload Locus.ipa
        uses: actions/upload-artifact@v4
        with:
          name: rename_to_Locus-DOT-ipa
          path: Locus.ipa
      
  gh:
    name: Update GitHub releases
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: To be done!
        run: |
          echo <3

  jb:
    name: Update jailbreak repository
    runs-on: ubuntu-latest
    needs: gh

    steps:
      - name: To be done!
        run: |
          echo <3

  alt:
    name: Update AltStore source
    runs-on: ubuntu-latest
    needs: gh

    steps:
      - name: To be done!
        run: |
          echo <3
  
  scarlet:
    name: Update Scarlet source
    runs-on: ubuntu-latest
    needs: gh

    steps:
      - name: To be done!
        run: |
          echo <3
