name: Build and release Locus

on: 
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check if Locus needs a re-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compare latest release
        run: |
          bash scripts/release_check.sh
      - name: Upload release2.txt
        uses: actions/upload-artifact@v4
        with:
          name: release2.txt
          path: release2.txt
  
  build:
    name: Build Locus
    runs-on: macos-14
    needs: check
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download release2.txt
        uses: actions/download-artifact@v4
        with:
          name: release2.txt
      - name: Update release.txt
        run: |
          mv -f release2.txt release.txt
      - name: Get Locus source code
        run: |
          mkdir gitignore && cd gitignore
          curl -LOJ $(curl -Ls https://api.github.com/repos/Myzel394/locus/releases/latest | grep \"zipball_url\" -m 1 | head -1 | tr -d ', ' | sed 's/"//g' | sed 's/zipball_url://g')
          unzip ./*.zip
          cd ./* && export MVDIR=$PWD
          cd .. && mv $MVDIR $MVDIR/../locus
          cd ${{ github.workspace }}
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2.0
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Build Locus
        run: |
          sudo xcodebuild -license accept && xcodebuild -downloadPlatform iOS
          cd gitignore/locus && flutter config --no-analytics && flutter --disable-telemetry && flutter build ipa --no-codesign && cd ${{ github.workspace }}
      - name: Upload source code with build folder
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: gitignore/locus
      - name: Create Locus IPA
        run: |
          cd gitignore/locus/build/ios/archive/Runner.xcarchive/Products
          mv ./Applications ./Payload
          zip -vr Locus.zip Payload -x "*.DS_Store"
          mv ./Locus.zip ${{ github.workspace }}/gitignore/Locus.ipa
      - name: Upload Locus IPA
        uses: actions/upload-artifact@v4
        with:
          name: Locus.ipa
          path: gitignore/Locus.ipa
      
  gh:
    name: Update GitHub releases
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: To be done!
        run: |
          echo \<\3

  alt:
    name: Update AltStore source
    runs-on: ubuntu-latest
    needs: gh

    steps:
      - name: To be done!
        run: |
          echo \<\3
  
  scarlet:
    name: Update Scarlet source
    runs-on: ubuntu-latest
    needs: gh

    steps:
      - name: To be done!
        run: |
          echo \<\3
